### ISSUE TITLE
ZIP Folder changes

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#382]
@ntgn81 Please remove the text file in the ZIP folder.  Please also store the references at the same level as the IDS and Transmittal Letter (i.e., get rid of the references folder so all documents are at the same level).  

Thanks!

**Comment by ntgn81** [comment]
@JulieJager , sorry, I missed this one. The text file has been removed. As for folders, we moved them into references folder just so you can easilly see the IDS forms themselves, otherwise the forms would be pushed down very far, depending on how many documents we have.

![image](https://cloud.githubusercontent.com/assets/4622542/17121079/eaa23fc8-529e-11e6-913d-1702ed3dc0f8.png)

**Comment by ntgn81** [comment]
It's an easy change if you want to make it flat!

**Comment by JulieJager** [comment]
@ntgn81 I see your point.  I went back to the old UI to see how Jim solved this problem.  It looks like he used an underscore for the IDS form.  If we do this for the IDS form and Transmittal Letter will that keep them at the top?

![capture](https://cloud.githubusercontent.com/assets/17907226/17122873/e8a82fc4-52a4-11e6-8ecf-9c6b3f806faa.JPG)

**Comment by ntgn81** [comment]
Sure, would you like to go with underscores then?

![image](https://cloud.githubusercontent.com/assets/4622542/17123462/a74043ca-52b1-11e6-9e14-f4fcd09dfc1f.png)

**Comment by JulieJager** [comment]
@ntgn81 Yes.  For testing at this point.

**Comment by ntgn81** [comment]
@JulieJager , please give it a try, it's updated

**Comment by JulieJager** [comment]
@ntgn81 That worked!  Great job.  Thank you.  I will test more later. :)
