### ISSUE TITLE
HIGH PRIORITY: S3 not creating/storing PDFs for new customer

### ISSUE THREAD

**Issue by JulieJager** [syncids/syncids-ui#634]
We migrated data for a new customer (globalpatentgroup.com) today.  
CLIENT: Horizon-RAVICTI
SQL says some foreign PDFs have been stored
UI shows the PDF icons in red but cannot view
S3 doesn't show globalpatentgroup.com as a customer at all hence no PDFs stored.

**Comment by ntgn81** [comment]
@JulieJager , what are you using to migrate data?

**Comment by JulieJager** [comment]
http://syncids.com/GetXForeignPDFs.asp?FirmName=**goedken**com&ClientNumber=**TEST**&Quantity=10

1.  We update the above link to force a PDF lookup after we migrate.
2.  Auto-overnight PDF look up does not seem to be working either.  Likely related. ?

**Comment by JulieJager** [comment]
First, I hate reporting bugs.  I know how I feel when I get them from our customer so - I'm sorry. But, I cannot release a 4 migrations until we figure out the S3 issue as the foreign PDF icons are red but nothing is there.   Are you close to figuring this one out?  I've done a lot of testing.  Only PDFs that are uploaded by customers are saved to S3, seems to be just our "look up" that is affected.

**Comment by ntgn81** [comment]
Don't be sorry! 

I only started looking at it. Not getting very far yet :(

**Comment by JulieJager** [comment]
I think its the old server clock.  I recall Jim telling me that the clock needs to be set within 5 minutes of the S3 (clock?).  Right now, we are 4 hour ahead.  I fixed the clock on Monday but I thought it crashed us somehow so I have not reset it.   I don't know why it sometimes goes 4 hours ahead (maybe when its reset).

**Comment by JulieJager** [comment]
A symptom of PDF issues is uploading PDFs to old UI but not being able to access.  I just confirmed I cannot access what I uploaded.  Shall I reset clock?  See what happens?  I just hope it does not affect the ability to generate IDS/Transmittal in new UI.  Worth a shot! ???

**Comment by ntgn81** [comment]
Hmm that very well be the problem. Transmital/IDS generation is still fine in new UI.

We can reset the clock and see what happens.

**Comment by ntgn81** [comment]
@JulieJager , the problem was indeed clock related - and it is solved.

The s3 upload script generate a timestamp at the moment of upload, and the current code was just

1. take server's time
2. add 5 hours to it - it assumes that the server's time is EST, hence adding 5 to make it GMT time. That does not always work, especially with daylight savings time.
3. S3 throws error "Request time and server time are too skewed", preventing the upload.

What I did to solve it:

1. Use a different script to calculate GMT timestamp (JScript)
2. Set the time of the server to EST time - I believe I can set server time to CST time too, to match with your time zones, if you'd prefer that.

Nam

**Comment by JulieJager** [comment]
YAY!  Thank you.  Thank you also for documenting the fix.  Leaving the time at EST is sufficient. :):):)
